# Generated by Django 5.0.9 on 2026-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
