# Generated by Django 5.0.9 on 2026-09-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_shops',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='shops.shop'),
        ),
    ]
