# Generated by Django 5.0.9 on 2026-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='shop_last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
