# Generated by Django 5.0.9 on 2026-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_walkin',
            field=models.BooleanField(default=False),
        ),
    ]
